### ISSUE TITLE
WhatsDeleted is not asking for notification permission and therefore not working on Xperia 10 II (XQ-AU52)

### ISSUE THREAD

**Issue by alexanderadam** [4nubhav/WhatsDeleted#16]
WhatsDeleted is not asking for notification permission and therefore not working on [Xperia 10 II (XQ-AU52)](https://www.sony.co.uk/electronics/smartphones/xperia-10m2).
It doesn't even seem to give the permission with another way.

It's running Android 10 if that's from interest.

**Comment by 4nubhav** [comment]
Hi! In case you haven't solved the problem, can you manually navigate to Settings > Apps & notifications > Special app access > Notification Access > WhatsDeleted & allow?

**Comment by alexanderadam** [comment]
It seems that it is resolved. :man_shrugging: 
(It wasn't my phone — I was just transmitting the bug request) :wink:
