### ISSUE TITLE
Notification Access switch keeps getting off everytime I open the app

### ISSUE THREAD

**Issue by drxgxn** [4nubhav/WhatsDeleted#2]
Notification Access switch keeps getting off everytime I open the app.

But when i go to system settings, the notification access switch is on for the whatsdeleted app.

So i have to toggle the switch off and on again to make the app work.

Sorry i dont know how to get logs. I am on one plus 3 oreo 8.0 Modified oxygenOS Rom.

**Comment by sunil-singh-chaudhary** [comment]
Did you get any solution and the other problem i found is it will show all whatsapp msg include delete one did you get any solution that too ??

**Comment by 4nubhav** [comment]
Even though the Notification Access switch keeps getting off every time you open the app, do the latest messages get added to the log?
