### ISSUE TITLE
Can't find msg log anymore

### ISSUE THREAD

**Issue by leandrodb** [4nubhav/WhatsDeleted#7]
I have a msgLog.txt in WhatsDeleted directory with 21Mb of messages before update to v0.2.

The log viewer on the other side shows only messages after the update. Ok, but where's this file? I need to search text in this new file like I did  in the old one, using an external txt viewer, but in version 0.2 I couldn't do it anymore.

If the new viewer could do text search, scroll down to latest logged messages, copy and paste, I wouldn't need to use an external text viewer.

But now I just need to open both files, the v0.1 and v0.2 msgLog.txt to find some deleted messages!

Thanks for the publicly licensed app and for the help here!

**Comment by 4nubhav** [comment]
Hi!

In `v0.2`, the `msgLog.txt` was moved to [app-specific storage](https://developer.android.com/training/data-storage) to prevent unauthorized access. So you can view the messages only through the app's viewer.

If you're confident that there will be no unauthorized access of your `msgLog.txt` & you'd like to use an external text editor, you can use `v0.1`

Also, I'll be releasing an update soon where the newest messages will be displayed first in the app's viewer, so you won't need to scroll down everytime.

Thanks for the appreciation.
